---
title: "Catálogo de datos (Open Metadata)"
--- 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,  fig.align="center", out.extra = 'style="display:block; margin:auto;"')
```

<div class=text-justify>

<br/>
<br/>


# Incorporación de la información (datos sintéticos) de las EPTPTASS a la herramienta de Catálogo de Datos (open metadata).



<br/>

# Mapeo de la información objetivo en el lago de datos (Harvesting).

Se habilitó la conexión al sistema de almacenamiento del LCiD donde se encuentran alojados los datos objeto de este caso de uso.

Se llevó a cabo un proceso de mapeo y recopilación de los metadatos estructurales de los archivos, con el fin de tener un panorama completo de los contenidos disponibles y su estructura.

Utilizando el diccionario de datos que nos proporcionaron, se añadieron las descripciones correspondientes a las columnas/variables de los archivos, permitiendo así una mejor comprensión y claridad en los metadatos estructurales.

<br/>

# Sección perfilado y calidad de los datos.
Se generaron muestras de información sobre las que se aplicaron algunas reglas básicas de perfilado y de calidad en las variables de Sexo, CURP y Nombre.


<br/>
