---
title: "Seguridad y Confidencialidad"
--- 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,  fig.align="center", out.extra = 'style="display:block; margin:auto;"')
```

<div class=text-justify>

<br/>

# Estrategia de Recolección de la Información.
****

## Insumos.

Información utilizada para el desarrollo del proyecto:

***1. Registro de Emisiones y Transferencia de Contaminantes (RETC).***

Tabla en formato Excel de las unidades económicas que reportan el uso y desecho de sustancias peligrosas o susceptibles de convertirse en peligrosas, para los años 2004 a 2016. Contiene la información de 3,529 registros.

Tabla de Emisiones y transferencias de los contaminantes (15,995 registros). Contiene los contaminantes que arrojan las UE al medio ambiente, su emisión, entre otros. Esta tabla se construye a partir de las emisiones de las unidades económicas, por lo que cada registro corresponde a una emisión y existen registros que se repiten tantas veces como sustancias se reportan.
