---
title: "Proyecto de Investigación: Aprovechamiento del lago de datos para la implementación de criterios de gobierno, seguridad, confidencialidad estadística, calidad e interoperabilidad de información"
--- 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,  fig.align="center", out.extra = 'style="display:block; margin:auto;"')
```

<div class=text-justify>

<br/>
<br/>

# 1. Objetivos

<br/>

## 1.1 Objetivo General
Desarrollar e implementar un prototipo que aproveche la tecnología de lago de datos para automatizar los flujos de trabajo, con el propósito de evaluar y aplicar criterios de gobierno de datos que permitan la integración e interoperabilidad de la información generada por el Instituto.


<br/>

## 1.2 Objetivos Específicos

1. Identificar los procesos, procedimientos, tecnología y roles relacionados con el gobierno de datos, en conjunto con las áreas correspondientes del Instituto.
2. Implementar flujos de datos que permitan verificar el grado de cumplimiento de los criterios de gobierno de datos.
3. Elaborar casos de uso que demuestren los beneficios de utilizar la tecnología de lago de datos para automatizar la aplicación de criterios de gobierno de datos en la integración de la información.
4. Crear un prototipo de servicios de acceso a datos dirigidos a los usuarios finales, que facilite el aprovechamiento completo de la gama de información de manera uniforme y coherente.

<br/>

# 2. Introducción

El presente reporte documenta el proyecto "Aprovechamiento del lago de datos para la implementación de criterios de gobierno, seguridad, confidencialidad estadística, calidad e interoperabilidad de información", desarrollado en el marco del Programa Anual de Investigación 2024 del Instituto. Este proyecto surge como respuesta a los desafíos que conlleva la modernización de los sistemas de producción y difusión de información estadística y geográfica, y busca capitalizar el uso de la tecnología de lago de datos para fortalecer la integración de información y la creación de nuevos productos.

La plataforma del lago de datos permitirá automatizar flujos de trabajo, facilitando la integración de múltiples fuentes y promoviendo la interoperabilidad entre diversas bases de datos. Al establecer criterios claros de gobierno de datos, el proyecto busca asegurar que la información generada cumpla con altos estándares de calidad, seguridad y confidencialidad estadística, respondiendo así tanto a las necesidades operativas como a las normativas vigentes. Esta estructura del lago de datos gobernado permitirá no solo una gestión más eficiente, sino también una mayor coherencia en el aprovechamiento de la información proveniente de diversos procesos de producción.

El prototipo desarrollado ofrecerá servicios de acceso orientados a los usuarios finales, permitiéndoles aprovechar de manera uniforme y consistente los datos disponibles. Esta aproximación permitirá a las áreas productoras trabajar de forma más efectiva al reducir redundancias y fomentar la reutilización de datos y metadatos, optimizando la producción y garantizando la actualización constante de la información que se genera.

El éxito del proyecto posicionará al lago de datos como un recurso estratégico para el INEGI, al consolidar un entorno de datos moderno, escalable y alineado con las mejores prácticas internacionales en la gestión de información. Con ello, se busca no solo mejorar la eficiencia interna, sino también potenciar la capacidad del Instituto para ofrecer productos y servicios innovadores que respondan a las necesidades de análisis actuales y futuras.

<br/>

# 3. Caso de uso: Estadística de Puestos de Trabajo y Plazas de Trabajadores Afiliados a la Seguridad Social (EPTPTASS)

El proceso denominado *Estadística de Puestos de Trabajo y Plazas de Trabajadores Afiliados a la Seguridad Social (EPTPTASS)* fue seleccionado como el caso de uso de prueba para evaluar la aplicabilidad de los criterios de gobierno de datos definidos en el proyecto. Esta estadística integra datos provenientes de diversas fuentes administrativas vinculadas al mercado laboral, lo que implica gestionar información compleja y heterogénea con altos estándares de calidad, confidencialidad y seguridad.

La implementación del prototipo en EPTPTASS permitirá representar flujos de trabajo orientados a la gestión de los datos, asegurando su integración coherente a través del lago de datos. A través de esta prueba se buscará verificar que los criterios de gobierno —como la trazabilidad, interoperabilidad, control de acceso y calidad— puedan ser aplicados de manera eficaz en escenarios reales. 

La EPTPTASS no solo representa un proceso de producción con relevancia técnica debido a los procedimientos que se aplican para la generación y uso de datos sintéticos, sino también una oportunidad para incidir en un proceso importante en el ámbito de la producción de información relacionada con el empleo y la seguridad social, que es un tema de interés permanente. Mediante el uso del prototipo, se espera obtener una gestión más eficiente y segura de los datos, garantizando que la información proporcionada a las unidades productoras y de análisis sea precisa, oportuna y consistente.

Los resultados obtenidos en este entorno permitirán validar la funcionalidad y escalabilidad del modelo para su aplicación en otros procesos de producción del Instituto. Esto contribuirá a consolidar el uso del lago de datos como una herramienta central en la producción, optimizando la operatividad interna y profundizando en la modernización de la producción de información del INEGI.

<br/>

## 3.1 Antecedentes

Texto sobre el desarrollo del proceso en etapas previas.

<br/>

## 3.2 Descripción inicial del proceso de producción

La documentación original del proceso de producción correspondiente a la generación de la Estadística de Puestos de Trabajo y Plazas de Trabajadores Afiliados a la Seguridad Social (EPTPTASS) describe y registra el flujo de actividades y datos tal como fue diseñado y ejecutado por el área responsable desde su inicio. Este documento refleja la comprensión interna del proceso sin haber sido alineado aún con criterios de gobierno de datos ni ajustado a estándares específicos.

El diagrama presentado a continuación fue elaborado en colaboración con el personal de la *Dirección General Adjunta de Registros Administrativos Sociodemográficos*, y muestra las fases, actividades y tareas tal como se llevaron a cabo cuando se ideó el proceso, ofreciendo una perspectiva clara de cómo el área mencionada gestionó la producción de esta estadística en su contexto operativo. Esta documentación permite comprender la estructura y secuencia de las acciones involucradas, facilitando la identificación de los procedimientos y datos que se producen, aunque todavía no incorpora las prácticas estandarizadas que se evaluarán en etapas posteriores del proyecto.Este modelado preliminar constituye la base sobre la cual se aplicarán los criterios de gobierno de datos definidos más adelante. 

<br>

<iframe src="https://ramegon76.github.io/modeptassorigin/index.html#diagram/ba6519c4-a3bb-4439-b928-56f9de7e3f8b" height="650" width="850" style="border: 1px solid #464646" allowfullscreen="" alt="Abrir en otra pestaña" data-external="1" scrolling="auto" ></iframe>

<br>
<br>

Según este diagrama, el proceso comienza con la generación de datos sintéticos a partir de un catálogo de nombres y apellidos proveniente de datos administrativos del IMSS. El resultado es un archivo de texto plano (.csv) que se importa en una tabla en la que se puede realizar una validación (curado) de datos en un entorno de Oracle, aplicando criterios establecidos previamente, mediante el uso de un script PL/SQL.

Posteriormente, la tabla con los datos ajustados se exporta nuevamente a un archivo de texto para ser combinada con nuevos datos sintéticos basados en registros administrativos del ISSSTE. Los datos resultantes se depositan en la bóveda digital para su procesamiento. Se adecúan los scripts para el diagnóstico y se inicia la etapa de pruebas de ejecución.

En esta etapa se buscó comparar la eficiencia de dos rutas de procesamiento (benchmark):

a) En la primera ruta, se prueba la funcionalidad del procesamiento usando las herramientas e infraestructura del entorno del lago de datos.
b) En la segunda opción, se explora la capacidad de procesamiento de los datos en un entorno local con acceso controlado.

Una vez ejecutados ambos tipos de procesamiento para calcular las estadísticas de puestos de trabajo, se comparan los rendimientos y tiempos de ejecución de ambas rutas, generando un reporte de resultados del comparativo de las eficiencias. La hipótesis del benchmark era que usar la infraestructura del lago de datos produce una mejor eficiencia del procesamiento, lo que efectivamente se comprobó.






